### ISSUE TITLE
Fail to load front-end page after “azd up” for sample "AspireShop"

### ISSUE THREAD

**Issue by faynef** [dotnet/aspire-samples#187]
**Describe the issue:**
Run the `azd up` command successed but clicking on the front-end page reports the following error:
![image](https://github.com/dotnet/aspire-samples/assets/138087452/f1cc93a5-4a8a-458d-8c0f-02bbdbdaec04)

**Repro Steps:**
1. Clone code (preview.5 branch).
2. `cd\samples\AspireShop`
3. `azd init`
4. `azd up`
5. click on the front link.

**Environment:**

- Azd version: `azd version 1.8.0-beta.1-daily.3669344 (commit 9dc2a31392349f383afce69d94b563c4d58afe4d)`
- Aspire version: `8.0.0-preview.5.24201.12/8.0.100`
- Sample: [AspireShop](https://github.com/dotnet/aspire-samples/tree/preview.5/samples/AspireShop)
- Branch: `preview.5`

**Expected behavior:**
The front-end page can load normally.

@rajeshkamal5050, @vhvb1989 for notification.

**Comment by davidfowl** [comment]
Can you show the logs?

**Comment by faynef** [comment]
Ok, figure below:
![image](https://github.com/dotnet/aspire-samples/assets/138087452/d80d7b06-c9cc-44d6-871d-66906e04c189)

**Comment by davidfowl** [comment]
I meant from the azure portal. It should show the exception.

**Comment by faynef** [comment]
Ok, figure below:
![image](https://github.com/dotnet/aspire-samples/assets/138087452/89649c1d-0281-4863-95ec-022eb644af34)
![image](https://github.com/dotnet/aspire-samples/assets/138087452/935db8fa-ae70-49d9-a768-1f0175e8a686)

**Comment by DamianEdwards** [comment]
It won't work because the PostgreSQL container is set to use a volume which currently doesn't work in ACA (specifically, the PostgreSQL container attempts to do a `chmod` during its initialization and that fails when using volumes in ACA). If you remove the call to `WithDataVolume()` for the PostgreSQL and Redis resources it should work.

**Comment by DamianEdwards** [comment]
I just verified this myself using the changes in the preview.6 branch and latest VS/azd bits. If you update the `Program.cs` of the AppHost project so that no password parameter is set and the `WithDataVolume()` method is not called, it deploys and runs successfully on ACA:

```csharp
var catalogDb = builder.AddPostgres("catalog")
    .AddDatabase("catalogdb");

var basketCache = builder.AddRedis("basketcache")
    .WithRedisCommander();
```

![image](https://github.com/dotnet/aspire-samples/assets/249088/77cf67ce-0b3a-448c-b181-f34d9146fbc5)
