### ISSUE TITLE
QUESTION:  in the DatabaseMigrations sample, why is this code so complex?

### ISSUE THREAD

**Issue by burtonrodman** [dotnet/aspire-samples#347]
I appreciate that sample of having a separate worker to apply database migrations.

My question is, why does this code seem to duplicate the logic of the in-built `context.Database.Migrate()`?  What does this gain us vs simpler code?  Is the canonical example not transactional?  Does breaking out the code provide better logging?

vs.

https://github.com/dotnet/aspire-samples/blob/main/samples/DatabaseMigrations/DatabaseMigrations.MigrationService/ApiDbInitializer.cs

Canonical example:
```
using (var scope = app.Services.CreateScope())
{
  var services = scope.ServiceProvider;

  var context = services.GetRequiredService<IngestionDbContext>();
  context.Database.Migrate();
}
```

**Comment by DamianEdwards** [comment]
AFAIK the sample breaks out the steps based on guidance from the EF Core team, and desire to ensure the migration occurs within an execution strategy (so it will be retried/resilient), and within an activity (so that traces it emits are grouped under 1 logical action).

I'm not sure if migrations are done within a transaction by default or not. Perhaps @AndriySvyryd can answer that.

**Comment by AndriySvyryd** [comment]
EF 8 doesn't provide resiliency during migration application and the transactions it uses aren't appropriate for an external retry strategy. This will be fixed for EF 9, so this code can be simplified, see https://github.com/dotnet/aspire-samples/issues/401

**Comment by burtonrodman** [comment]
thanks for the explanation!
