### ISSUE TITLE
Inconsistent Database Behavior - 'DB does not exist' Error vs. Data Visibility in eShopLite UI

### ISSUE THREAD

**Issue by josephaw1022** [dotnet/aspire-samples#43]
I'm encountering an unusual issue with the catalog database in our project. It manifests in several conflicting ways:

1. **Database Existence Error**: The primary concern is an error message stating "database does not exist." This error appears in the logs, but the exact circumstances leading to this error are unclear. A screenshot of the error can be found here: [Database Error Screenshot](https://github.com/dotnet/aspire-samples/assets/47674962/0df5130a-c56f-41df-aa04-a1513b44f923).

2. **Database Visibility in pgAdmin**: Contradicting the error, when I inspect the database through pgAdmin, the database seems intact. This might indicate a permissions issue with PostgreSQL, but I'm not certain. Here's a screenshot of the pgAdmin view: [pgAdmin View Screenshot](https://github.com/dotnet/aspire-samples/assets/47674962/12e27bd4-dc51-434a-a297-a9a8008a6874).

3. **Data Seeding and UI Interaction**: Further adding to the confusion, when I access the UI immediately after data seeding, the catalog data is present and correctly displayed in the eShopLite UI. This suggests that the database is not only created but also accessible by the catalog service.

**Conclusion and Request for Assistance**:
The logs in the Aspire dashboard are indicating a missing database, which is in direct conflict with both the pgAdmin view and the UI behavior. This inconsistency is perplexing, and I am seeking insights or suggestions on how to resolve or further diagnose this issue.

**Comment by DamianEdwards** [comment]
These messages are printed when a connection is attempted by the catalogservice or catalogdbmanager apps before the database has been created by catalogdbmanager, i.e. it's a race condition (albeit an expected one).

As is common in distributed systems, there is no coordination between the lifetime of dependent resources, so the PostgreSQL container can start before or after the catalogdbmanager starts. With this in mind, the catalogdbmanager kicks off a background job when it starts up to run EF migrations, which include initializing (i.e. creating) the database if it doesn't exist.

If you turn up the logging level for EF Core in the catalogdbmanager project (by adding a line like `"Microsoft.EntityFrameworkCore": "Trace"`  to *appsettings.Development.json* under the `"LogLevel"` node), you can see what's happening:

<img width="1028" alt="image" src="https://github.com/dotnet/aspire-samples/assets/249088/c02f4a8c-4db1-4c5b-b1e0-4437b2d1df63">

- It first attempts to connect to database "catalogdb" and fails (twice, likely due to default retries)
- It then attempts to connect to database "postgres" instead, which is the default on PostgreSQL, and succeeds
- It executes some commands include a `CREATE DATABASE catalogdb;` which can be seen by opening the details of the message in the Structured Logs page
- It disconnects from the "postgres" database and opens a new connection to the "catalogdb" database to continue with database initialization
